### ISSUE TITLE
Assets/UTNotifications/Src/WSA/WSAManagerImpl.cs(7,23): error CS0234: The type or namespace name `WSA' does not exist in the namespace `UTNotifications'. Are you missing an assembly reference?

### ISSUE THREAD

**Issue by jondewoo** [universal-tools/UTNotificationsFeedback#29]
Hi,

I'm getting an error while building for WP 8.1 (Net Core): Assets/UTNotifications/Src/WSA/WSAManagerImpl.cs(7,23): error CS0234: The type or namespace name `WSA' does not exist in the namespace`UTNotifications'. Are you missing an assembly reference?

Seems like 'WSA_PLUGIN' is not defined, but adding it to the 'Scripting Define Symbols' yields other compilation errors.

Please advise.

**Comment by yuriy-universal-ivanov** [comment]
Hi @jderrough,

WSA_PLUGIN should **not** be defined in Unity, it's enabled only when building the native plugin's .winmd library. The issue in your case is that Unity, by some reason, didn't import both runtime .winmd and editor .dll Windows Store plugins of UTNotifications.

Could you please tell me what version of UTNotifications and Unity you use? As we fixed similar issue with latest versions of Unity in the recently released UTNotifications 1.6.

Best regards,
Yuriy, Universal Tools team.

**Comment by jondewoo** [comment]
Hi @yuriy-universal-ivanov,

Thanks for your response.

I'm using UTNotifications 1.6 with Unity 5.3.6f1. I tried reimporting UTNotifications from the store, still getting the error when building.
The runtime .winmd and editor .dll Windows Store plugins of UTNotifications are part of the project and are configured correctly, it seems, respectively: WSAPlayer and Editor.

**Comment by yuriy-universal-ivanov** [comment]
Hi @jderrough,

I just tried: installed Unity 5.3.6, created a new project, imported UTNotifications 1.6 there and built with the same settings (WP 8.1 Net Core) - works completely fine.

Could you please try doing the same? If it works, please send to [universal.tools.contact@gmail.com](mailto:universal.tools.contact@gmail.com) the sample project which reproduces the issue, so we'll have something to research. If not, please tell me your version of Windows, Visual Studio and Windows Phone 8.1 SDK.

P.S. Please also make sure, that .Net Scripting Backend is chosen in the Platform Settings (as IL2CPP Scripting Backend is not supported on Windows Store, though UTNotifications should have informed you about it in the output console in that case).

Best regards,
Yuriy, Universal Tools team.

**Comment by jondewoo** [comment]
Hi @yuriy-universal-ivanov ,

Sorry, I got a bit confused between different tests in my initial post: the 'Compilation Overrides' is actually set to 'None' and 'Scripting Backend' to '.Net'. The error can be reproduced with an empty project by importing UTNotifications 1.6 and building for WP 8.1.

Best,
Jonathan

**Comment by yuriy-universal-ivanov** [comment]
Hi @jderrough,

Oh, OK, now I see. "Net Core" or "Net Core Partially" are required for our asset. Can you use any of these options?

Best regards,
Yuriy, Universal Tools team.

**Comment by jondewoo** [comment]
Hi @yuriy-universal-ivanov ,

This is not an option as other SDKs won't work in "Net Core", like the Facebook SDK, Stan's Assets, or MonsterLove's State Machine to name a few.
Is there anything you can do on your end?

Best,
Jonathan

**Comment by yuriy-universal-ivanov** [comment]
Hi @jderrough,

Please find a file Assets/Plugins/WSA/UTNotifications.winmd in Unity Projects view, and specify its placeholder: **Assets/Plugins/UTNotifications.dll**, and press "Apply".

Disabling "Unity C# Projects" in Unity building dialog may be required.

It helped building my test project with Compilation Overwrites set to None.

Best regards,
Yuriy, Universal Tools team.

**Comment by jondewoo** [comment]
Hi @yuriy-universal-ivanov ,

That did the trick! :)

Thank you very much.

Best,
Jonathan
